

post http://localhost:3000/user/signup
Content-Type: application/json

{
  "username": "sikkkram_9",
  "name": "sriramsudha",
  "password": "sri@123",
  "gender": "male"
}

######

POST  http://localhost:3000/user/login/
Content-Type: application/json

{
  "username": "sikkkram_9",
  "password": "sri@123"
}

####
GET  http://localhost:3000/user/profile
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNpa2trcmFtXzkiLCJpYXQiOjE3MDk3NDgyMTN9.1K2zaj5ltDEYhgt_inD8Rh34d6YoLEjHpBQPCSHmEoQ

####
GET  http://localhost:3000/recipe/recipes
Content-Type:application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNpa2trcmFtXzkiLCJpYXQiOjE3MDk3NDgyMTN9.1K2zaj5ltDEYhgt_inD8Rh34d6YoLEjHpBQPCSHmEoQ


####
POST http://localhost:3000/recipe/add-recipe
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNpa2trcmFtXzkiLCJpYXQiOjE3MDk3NDgyMTN9.1K2zaj5ltDEYhgt_inD8Rh34d6YoLEjHpBQPCSHmEoQ

{
    "title": "vada22",
    "description": "Tasty yummy diet food",
    "ingredients": "mirchi,ginger,salt,oil",
    "instructions": "boil the water to a heating point then put the pasta into it",
    "images": "image_url1"
}
####

PUT  http://localhost:3000/recipe/update/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNpa2trcmFtXzkiLCJpYXQiOjE3MDk3NDgyMTN9.1K2zaj5ltDEYhgt_inD8Rh34d6YoLEjHpBQPCSHmEoQ

{
    "title": "gista",
    "description": "Tasty yummy diet food",
    "ingredients": "mirchi,ginger,salt,oil",
    "instructions": "boil the water to a heating point then put the pasta into it",
    "images": "image_url1"
}


###
DELETE http://localhost:3000/recipe/delete/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNpa2trcmFtXzkiLCJpYXQiOjE3MDk3NDgyMTN9.1K2zaj5ltDEYhgt_inD8Rh34d6YoLEjHpBQPCSHmEoQ
